#ifndef CONFIG_H
#define CONFIG_H

#define HAVE_CPUID_INTRINSIC 1
#define HAVE_PTHREAD_SETSCHEDPARAM 0
#define HAVE_PTHREAD_SETNAME_NP 0
#define HAVE_PTHREAD_SET_NAME_NP 0
#define HAVE_CPUID_H 0
#define HAVE_GUIDDEF_H 0
#define HAVE_INTRIN_H 0
#define HAVE_PTHREAD_NP_H 0
#define HAVE_DLFCN_H 0

#endif
