name: Build

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@main

    - name: Configure CMake and Build
      run: bash android_ci_build.bash

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: openal
        path: lib
